/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Public and static. Touches no database on purpose: an unauthenticated endpoint that queried Postgres would be a free DDoS amplifier.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * How every number in this API is calculated
         * @description Metric formulas, the windows and weighting behind them, the mart filters that decide which rows reach an aggregate, the units, and the standing caveats. Read this before explaining a figure to a user: it is the difference between describing our methodology and inventing a plausible one. Assembled from the constants that define the behaviour, so it cannot drift from what the code actually does.
         */
        get: operations["metrics_meta_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What the dataset actually contains
         * @description Date ranges, row counts, source cutovers and geo coverage. Read this before answering questions about a period: it is how a client learns where the data stops instead of extrapolating past it.
         */
        get: operations["coverage_meta_coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange credentials for tokens */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trade a refresh token for a new access token */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dimensions/areas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List areas */
        get: operations["list_areas_dimensions_areas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dimensions/areas/{area_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one area */
        get: operations["get_area_dimensions_areas__area_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dimensions/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List projects */
        get: operations["list_projects_dimensions_projects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dimensions/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one project */
        get: operations["get_project_dimensions_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dimensions/buildings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List buildings */
        get: operations["list_buildings_dimensions_buildings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dimensions/buildings/{building_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one building */
        get: operations["get_building_dimensions_buildings__building_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dimensions/developers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List developers */
        get: operations["list_developers_dimensions_developers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dimensions/property-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List property types */
        get: operations["list_property_types_dimensions_property_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dimensions/usages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the real `usage` values
         * @description The distinct usage values actually present, unnormalized. Call this before filtering by usage: the vocabulary is messy and there is no 'office' category, so guessing a value silently returns nothing.
         */
        get: operations["list_usages_dimensions_usages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dimensions/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List data sources */
        get: operations["list_sources_dimensions_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/facts/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Individual sale transactions
         * @description Drill-down and evidence, not bulk export. Requires at least one of area_id, project_id or a date lower bound so the query uses an index; `total` is never computed on these 12M-row tables.
         */
        get: operations["list_transactions_facts_transactions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/facts/rents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Individual rent contracts
         * @description Drill-down and evidence, not bulk export. Requires at least one of area_id, project_id or a date lower bound so the query uses an index; `total` is never computed on these 12M-row tables.
         */
        get: operations["list_rents_facts_rents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/marts/area-monthly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Monthly series for a set of areas */
        get: operations["area_monthly_marts_area_monthly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/marts/project-monthly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Monthly series for a set of projects */
        get: operations["project_monthly_marts_project_monthly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/marts/building-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Price summary per building — not a time series
         * @description One row per (building, usage): a trailing-12-month price level, lifetime coverage, and a coarse CAGR that is null unless the sample supports it.
         *
         *     The shape differs from the monthly marts deliberately. A monthly grain was measured and rejected — 42% of (building, month, usage) cells would hold exactly one sale, so a 'median' there is just that sale. Do not plot this as a series.
         *
         *     Sales only, permanently: no rent contract carries a building identifier, so yield cannot be computed at this grain.
         */
        get: operations["building_summary_marts_building_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/area-ranking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Rank areas, projects or buildings by an investment metric
         * @description Answers 'which area has the best ROI over the last N years' and — with ascending=true and metric=sale_price_m2 — 'where is the cheapest part of Dubai'. Buildings support only capital_growth and sale_price_m2: no rent contract carries a building identifier, so income metrics cannot exist at that grain.
         */
        get: operations["area_ranking_analytics_area_ranking_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/growth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Time series, CAGR and year-over-year steps for one entity
         * @description Answers 'which project's rent rises every year' — see `consecutive_yoy_increases`.
         */
        get: operations["growth_analytics_growth_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/yield": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Rank by gross rental yield
         * @description Gross: before service charges, vacancy, fees and the 4% DLD transfer fee.
         */
        get: operations["yields_analytics_yield_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Side-by-side metrics across usages, entities, or mixed types
         * @description Answers 'is it better to invest in X or Y'. For usage comparisons, call /dimensions/usages first — the vocabulary is raw and there is no 'office' category to compare against.
         *
         *     Use `dimension=mixed` to compare across types: values become `type:value` specs such as `project:412,area:Dubai Marina`. That is how you ask whether a development is beating the neighbourhood it sits in, which single-type comparison cannot express.
         */
        get: operations["compare_analytics_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geo/areas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Areas as GeoJSON, with metrics as feature properties
         * @description One request renders a choropleth: geometry and the latest qualifying metrics arrive together, so there is no per-polygon follow-up call. The geo filter is implicit — areas without geometry are absent.
         */
        get: operations["areas_geojson_geo_areas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geo/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Projects as GeoJSON points
         * @description Each feature carries geo_match_method + is_precise, and for building-derived points geo_building_count / geo_spread_m — so the map distinguishes precise pins from the coarse area-centroid backbone and knows when a project is really a broad footprint.
         */
        get: operations["projects_geojson_geo_projects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geo/buildings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buildings as GeoJSON points
         * @description Makani-geocoded buildings for building-level zoom. Only precise (makani_validated) buildings have a point, so this never returns a coarse location. Scope with area_id when zoomed into one area.
         */
        get: operations["buildings_geojson_geo_buildings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Anchor
         * @description One end of the growth measurement.
         */
        Anchor: {
            /** Value Aed M2 */
            value_aed_m2?: number | null;
            /**
             * Sample Size
             * @default 0
             */
            sample_size: number;
            /**
             * Midpoint
             * @description Count-weighted centre of the anchor window.
             */
            midpoint?: string | null;
            /**
             * Months
             * @default 0
             */
            months: number;
        };
        /**
         * Area
         * @description A DLD community/area — the primary unit of geographic analysis.
         */
        Area: {
            /**
             * Has Geo Data
             * @description Any geometry present — renderable at least as a point.
             */
            has_geo_data: boolean;
            /**
             * Has Boundary
             * @description A polygon boundary is present. Required for choropleths; materially fewer entities have this than have a centroid.
             */
            has_boundary: boolean;
            /** Id */
            id: number;
            /**
             * Dld Area Code
             * @description DLD code, e.g. 'A-292'.
             */
            dld_area_code?: string | null;
            /**
             * Name En
             * @description Canonical UPPER-cased English name.
             */
            name_en: string;
            /** Name Ar */
            name_ar?: string | null;
            /** Zone Name */
            zone_name?: string | null;
            /**
             * Geo Match Method
             * @description How geometry was matched to this area: exact | parent_fallback | manual. parent_fallback means the shape belongs to a larger parent area, so it is approximate.
             */
            geo_match_method?: string | null;
            /**
             * Superseded Areas
             * @description Old DLD codes whose activity is now reported under this area, because DLD re-coded the community (AREA_CODE_MIGRATION_ANALYSIS.md). Empty for an area that was never split.
             */
            superseded_areas?: components["schemas"]["AreaLineageRef"][];
            /**
             * Superseded By
             * @description Set only when this area itself is an old, superseded code: every current area its activity may now be reported under — a list because DLD subdivides, not renames, and an old area can have several successors (21 of 48 split areas do). This area's own id/name/code are still returned as-is — lookups by an old code are never redirected, only annotated. When there is more than one successor, this old area's own aggregated figures (area-scoped facts/marts/analytics) are not resolvable to a single canonical area and querying them raises an ambiguity error naming this same list.
             */
            superseded_by?: components["schemas"]["AreaLineageRef"][] | null;
        };
        /**
         * AreaLineageRef
         * @description A minimal pointer to another area, used for area-code migration
         *     lineage (AREA_CODE_MIGRATION_ANALYSIS.md).
         */
        AreaLineageRef: {
            /** Id */
            id: number;
            /** Dld Area Code */
            dld_area_code?: string | null;
            /** Name En */
            name_en: string;
        };
        /**
         * Building
         * @description A building — the addressable unit that carries a precise location.
         *
         *     `is_precise` is true only for a Makani-validated point; a building with
         *     `has_geo_data=false` is in the attribute register but not yet geocoded.
         */
        Building: {
            /** Id */
            id: number;
            /** Name En */
            name_en: string;
            /** Name Ar */
            name_ar?: string | null;
            /** Area Id */
            area_id?: number | null;
            /** Area Name En */
            area_name_en?: string | null;
            /** Project Id */
            project_id?: number | null;
            /** Project Name En */
            project_name_en?: string | null;
            /**
             * Geo Match Method
             * @description 'makani_validated' for a precise point, else null.
             */
            geo_match_method?: string | null;
            /**
             * Is Precise
             * @description True only for a Makani-validated location.
             */
            is_precise: boolean;
            /** Has Geo Data */
            has_geo_data: boolean;
            /** Built Up Area */
            built_up_area?: string | null;
            /** Floors */
            floors?: number | null;
            /** Flats */
            flats?: number | null;
            /** Offices */
            offices?: number | null;
            /** Shops */
            shops?: number | null;
            /** Car Parks */
            car_parks?: number | null;
            /** Elevators */
            elevators?: number | null;
            /** Swimming Pools */
            swimming_pools?: number | null;
            /** Is Free Hold */
            is_free_hold?: boolean | null;
            /**
             * Rooms
             * @description Villa-typical room count, e.g. '3 B/R'.
             */
            rooms?: string | null;
        };
        /** BuildingSummaryPage */
        BuildingSummaryPage: {
            /** Items */
            items: components["schemas"]["BuildingSummaryRow"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Has More */
            has_more: boolean;
            /** Total */
            total?: number | null;
            applied: components["schemas"]["MartApplied"];
            /**
             * Grain
             * @description Stated in the payload so a client cannot mistake it.
             */
            grain: string;
            /** Sales Only */
            sales_only: string;
            /** Requested Ids */
            requested_ids?: number[] | null;
            /** Returned Ids */
            returned_ids?: number[] | null;
            /** Missing Ids */
            missing_ids?: number[] | null;
        };
        /**
         * BuildingSummaryRow
         * @description One (building, usage) summary — NOT a month of a time series.
         *
         *     Deliberately a different shape from `MartRow`. At building level a monthly
         *     grain collapses into noise (42% of cells would hold one sale), so what is
         *     published is a current price level, lifetime coverage, and a coarse trend
         *     that is null unless the sample supports it.
         *
         *     There are no rent or yield fields and there never will be: the source rent
         *     data carries no building identifier to join on.
         */
        BuildingSummaryRow: {
            /** Entity Id */
            entity_id: number;
            /** Name En */
            name_en: string;
            /** Area Id */
            area_id?: number | null;
            /** Area Name En */
            area_name_en?: string | null;
            /** Usage */
            usage: string;
            /**
             * Sale Cnt 12M
             * @description Sales in the trailing 12 months — the price level's sample.
             */
            sale_cnt_12m?: number | null;
            /** Median Price M2 12M */
            median_price_m2_12m?: string | null;
            /** P25 Price M2 12M */
            p25_price_m2_12m?: string | null;
            /** P75 Price M2 12M */
            p75_price_m2_12m?: string | null;
            /**
             * Sale Cnt Total
             * @description Lifetime sales on record.
             */
            sale_cnt_total: number;
            /** Median Price M2 All */
            median_price_m2_all?: string | null;
            /** First Sale */
            first_sale?: string | null;
            /** Last Sale */
            last_sale?: string | null;
            /**
             * Price M2 Cagr Pct
             * @description Null unless the history spans >= 2 years AND both anchor windows hold >= 5 sales. A null here means 'cannot be stated honestly', not 'zero growth'.
             */
            price_m2_cagr_pct?: string | null;
            /** Cagr Years */
            cagr_years?: string | null;
            /** Cagr Sample Size */
            cagr_sample_size?: number | null;
            /**
             * Sample Tier
             * @description strong (>=20 sales in 12m) / thin (>=5) / insufficient. Quote 'thin' and 'insufficient' figures with that caveat attached.
             */
            sample_tier: string;
        };
        /** CompareGroup */
        CompareGroup: {
            /**
             * Capital Growth Cagr Pct
             * @description Annualized growth of the median sale AED/m2 between count-weighted anchor windows. Null when the span is under a year or there is not enough data — never a guess.
             */
            capital_growth_cagr_pct?: number | null;
            /**
             * Gross Rental Yield Pct
             * @description Median annual rent AED/m2 over median sale AED/m2, latest 12 months. GROSS: before service charges, vacancy and fees.
             */
            gross_rental_yield_pct?: number | null;
            /**
             * Gross Total Return Pct
             * @description capital_growth_cagr_pct + gross_rental_yield_pct, the NCREIF/MSCI income+capital decomposition. Null unless both halves exist — a missing half is never treated as zero.
             */
            gross_total_return_pct?: number | null;
            /** Median Sale Aed M2 */
            median_sale_aed_m2?: number | null;
            /** Median Rent Aed M2 Year */
            median_rent_aed_m2_year?: number | null;
            /**
             * Years
             * @description Span between anchor midpoints.
             */
            years?: number | null;
            start?: components["schemas"]["Anchor"] | null;
            end?: components["schemas"]["Anchor"] | null;
            /**
             * Sale Sample Size
             * @default 0
             */
            sale_sample_size: number;
            /**
             * Rent Sample Size
             * @default 0
             */
            rent_sample_size: number;
            /**
             * Months Covered
             * @default 0
             */
            months_covered: number;
            /** Month From */
            month_from?: string | null;
            /** Month To */
            month_to?: string | null;
            /** Value */
            value: string;
            /** Id */
            id?: number | null;
            /** Name En */
            name_en?: string | null;
            /**
             * Entities Pooled
             * @description Areas pooled into this group (usage comparisons).
             */
            entities_pooled?: number | null;
            resolved_entity?: components["schemas"]["ResolvedEntity"] | null;
        };
        /** CompareResponse */
        CompareResponse: {
            /** Methodology */
            methodology: string;
            /**
             * Caveats
             * @description Limitations that must be repeated alongside any number here.
             */
            caveats: string[];
            /** Dimension */
            dimension: string;
            /** Groups */
            groups: components["schemas"]["CompareGroup"][];
            /** Applied */
            applied: {
                [key: string]: unknown;
            };
        };
        /** Developer */
        Developer: {
            /** Id */
            id: number;
            /** Dld Number */
            dld_number?: number | null;
            /** Name En */
            name_en: string;
            /** Name Ar */
            name_ar?: string | null;
        };
        /**
         * EntityCandidate
         * @description One fuzzy-match candidate, with the score that produced it.
         */
        EntityCandidate: {
            /** Id */
            id: number;
            /** Name En */
            name_en: string;
            /**
             * Similarity
             * @description pg_trgm trigram similarity, 0..1. Higher is closer.
             */
            similarity: number;
        };
        /** GrowthResponse */
        GrowthResponse: {
            /** Methodology */
            methodology: string;
            /**
             * Caveats
             * @description Limitations that must be repeated alongside any number here.
             */
            caveats: string[];
            /**
             * Capital Growth Cagr Pct
             * @description Annualized growth of the median sale AED/m2 between count-weighted anchor windows. Null when the span is under a year or there is not enough data — never a guess.
             */
            capital_growth_cagr_pct?: number | null;
            /**
             * Gross Rental Yield Pct
             * @description Median annual rent AED/m2 over median sale AED/m2, latest 12 months. GROSS: before service charges, vacancy and fees.
             */
            gross_rental_yield_pct?: number | null;
            /**
             * Gross Total Return Pct
             * @description capital_growth_cagr_pct + gross_rental_yield_pct, the NCREIF/MSCI income+capital decomposition. Null unless both halves exist — a missing half is never treated as zero.
             */
            gross_total_return_pct?: number | null;
            /** Median Sale Aed M2 */
            median_sale_aed_m2?: number | null;
            /** Median Rent Aed M2 Year */
            median_rent_aed_m2_year?: number | null;
            /**
             * Years
             * @description Span between anchor midpoints.
             */
            years?: number | null;
            start?: components["schemas"]["Anchor"] | null;
            end?: components["schemas"]["Anchor"] | null;
            /**
             * Sale Sample Size
             * @default 0
             */
            sale_sample_size: number;
            /**
             * Rent Sample Size
             * @default 0
             */
            rent_sample_size: number;
            /**
             * Months Covered
             * @default 0
             */
            months_covered: number;
            /** Month From */
            month_from?: string | null;
            /** Month To */
            month_to?: string | null;
            /** Entity */
            entity: string;
            /** Id */
            id: number;
            /** Name En */
            name_en?: string | null;
            /** Series */
            series: components["schemas"]["SeriesPoint"][];
            /** Yoy */
            yoy: components["schemas"]["YoYStep"][];
            /**
             * Consecutive Yoy Increases
             * @description Run of consecutive rising years ending at the most recent year — answers 'does this keep going up every year' directly.
             */
            consecutive_yoy_increases: number;
            resolved_entity?: components["schemas"]["ResolvedEntity"] | null;
            /** Applied */
            applied: {
                [key: string]: unknown;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** MartApplied */
        MartApplied: {
            /** Min Sample */
            min_sample?: number | null;
            /**
             * Include Future
             * @default false
             */
            include_future: boolean;
        };
        /** MartPage */
        MartPage: {
            /** Items */
            items: components["schemas"]["MartRow"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Has More */
            has_more: boolean;
            /** Total */
            total?: number | null;
            applied: components["schemas"]["MartApplied"];
            /**
             * Requested Ids
             * @description The ids asked for, echoed back.
             */
            requested_ids?: number[] | null;
            /**
             * Returned Ids
             * @description Ids that actually produced rows.
             */
            returned_ids?: number[] | null;
            /**
             * Missing Ids
             * @description Requested ids with no matching mart rows. Surface these as 'no data' per selection rather than dropping the series.
             */
            missing_ids?: number[] | null;
        };
        /**
         * MartRow
         * @description One (entity, month, usage) cell of the monthly time series.
         *
         *     Always read `sale_cnt` / `rent_cnt` before trusting a median: some months
         *     contain a single transaction, and its "median" is just that one price.
         */
        MartRow: {
            /** Entity Id */
            entity_id: number;
            /** Name En */
            name_en: string;
            /**
             * Month
             * Format: date
             * @description First day of the month.
             */
            month: string;
            /** Usage */
            usage: string;
            /**
             * Sale Cnt
             * @description Sales behind the sale medians.
             */
            sale_cnt?: number | null;
            /** Sale Median Price M2 */
            sale_median_price_m2?: string | null;
            /** Sale P25 Price M2 */
            sale_p25_price_m2?: string | null;
            /**
             * Sale P75 Price M2
             * @description With p25, the spread — a wide band means a mixed month.
             */
            sale_p75_price_m2?: string | null;
            /**
             * Rent Cnt
             * @description Contracts behind the rent median.
             */
            rent_cnt?: number | null;
            /** Rent Median Annual M2 */
            rent_median_annual_m2?: string | null;
            /**
             * Gross Yield Pct
             * @description rent_median_annual_m2 / sale_median_price_m2, gross.
             */
            gross_yield_pct?: string | null;
        };
        /** Page[Area] */
        Page_Area_: {
            /** Items */
            items: components["schemas"]["Area"][];
            /**
             * Total
             * @description Total matching rows, when cheap to compute. Null on large fact scans where counting would cost as much as the query itself.
             */
            total?: number | null;
            /**
             * Limit
             * @description Max rows this response may contain.
             */
            limit: number;
            /**
             * Offset
             * @description Rows skipped before the first item.
             */
            offset: number;
            /**
             * Has More
             * @description True if more rows exist past this page.
             */
            has_more: boolean;
        };
        /** Page[Building] */
        Page_Building_: {
            /** Items */
            items: components["schemas"]["Building"][];
            /**
             * Total
             * @description Total matching rows, when cheap to compute. Null on large fact scans where counting would cost as much as the query itself.
             */
            total?: number | null;
            /**
             * Limit
             * @description Max rows this response may contain.
             */
            limit: number;
            /**
             * Offset
             * @description Rows skipped before the first item.
             */
            offset: number;
            /**
             * Has More
             * @description True if more rows exist past this page.
             */
            has_more: boolean;
        };
        /** Page[Developer] */
        Page_Developer_: {
            /** Items */
            items: components["schemas"]["Developer"][];
            /**
             * Total
             * @description Total matching rows, when cheap to compute. Null on large fact scans where counting would cost as much as the query itself.
             */
            total?: number | null;
            /**
             * Limit
             * @description Max rows this response may contain.
             */
            limit: number;
            /**
             * Offset
             * @description Rows skipped before the first item.
             */
            offset: number;
            /**
             * Has More
             * @description True if more rows exist past this page.
             */
            has_more: boolean;
        };
        /** Page[Project] */
        Page_Project_: {
            /** Items */
            items: components["schemas"]["Project"][];
            /**
             * Total
             * @description Total matching rows, when cheap to compute. Null on large fact scans where counting would cost as much as the query itself.
             */
            total?: number | null;
            /**
             * Limit
             * @description Max rows this response may contain.
             */
            limit: number;
            /**
             * Offset
             * @description Rows skipped before the first item.
             */
            offset: number;
            /**
             * Has More
             * @description True if more rows exist past this page.
             */
            has_more: boolean;
        };
        /** Page[PropertyType] */
        Page_PropertyType_: {
            /** Items */
            items: components["schemas"]["PropertyType"][];
            /**
             * Total
             * @description Total matching rows, when cheap to compute. Null on large fact scans where counting would cost as much as the query itself.
             */
            total?: number | null;
            /**
             * Limit
             * @description Max rows this response may contain.
             */
            limit: number;
            /**
             * Offset
             * @description Rows skipped before the first item.
             */
            offset: number;
            /**
             * Has More
             * @description True if more rows exist past this page.
             */
            has_more: boolean;
        };
        /** Page[RentContract] */
        Page_RentContract_: {
            /** Items */
            items: components["schemas"]["RentContract"][];
            /**
             * Total
             * @description Total matching rows, when cheap to compute. Null on large fact scans where counting would cost as much as the query itself.
             */
            total?: number | null;
            /**
             * Limit
             * @description Max rows this response may contain.
             */
            limit: number;
            /**
             * Offset
             * @description Rows skipped before the first item.
             */
            offset: number;
            /**
             * Has More
             * @description True if more rows exist past this page.
             */
            has_more: boolean;
        };
        /** Page[SaleTransaction] */
        Page_SaleTransaction_: {
            /** Items */
            items: components["schemas"]["SaleTransaction"][];
            /**
             * Total
             * @description Total matching rows, when cheap to compute. Null on large fact scans where counting would cost as much as the query itself.
             */
            total?: number | null;
            /**
             * Limit
             * @description Max rows this response may contain.
             */
            limit: number;
            /**
             * Offset
             * @description Rows skipped before the first item.
             */
            offset: number;
            /**
             * Has More
             * @description True if more rows exist past this page.
             */
            has_more: boolean;
        };
        /**
         * Project
         * @description A development project. Master projects contain sub-projects.
         */
        Project: {
            /**
             * Has Geo Data
             * @description Any geometry present — renderable at least as a point.
             */
            has_geo_data: boolean;
            /**
             * Has Boundary
             * @description A polygon boundary is present. Required for choropleths; materially fewer entities have this than have a centroid.
             */
            has_boundary: boolean;
            /** Id */
            id: number;
            /** Dld Project Number */
            dld_project_number?: number | null;
            /** Name En */
            name_en: string;
            /** Name Ar */
            name_ar?: string | null;
            /**
             * Master Project Id
             * @description Parent project id, when this is a sub-project.
             */
            master_project_id?: number | null;
            /** Master Project En */
            master_project_en?: string | null;
            /**
             * Is Master
             * @description True for master developments. The same name can exist as both a master and a regular project, so this disambiguates.
             */
            is_master: boolean;
            /** Area Id */
            area_id?: number | null;
            /** Developer Id */
            developer_id?: number | null;
            /** Status */
            status?: string | null;
            /** Project Type */
            project_type?: string | null;
            /** Percent Completed */
            percent_completed?: string | null;
            /** Cnt Units */
            cnt_units?: number | null;
            /** Completion Date */
            completion_date?: string | null;
            /**
             * Geo Match Method
             * @description How `location` was placed. Precise: 'building_point' / 'building_centroid' (Makani building rollup) and 'master_of_children'; 'nominatim_validated' (OSM name match). Coarse: 'area_centroid', a fallback shared by every project in the area — do not render as precise. Null means no location yet.
             */
            geo_match_method?: string | null;
            /**
             * Geo Building Count
             * @description Validated buildings behind a building-derived point.
             */
            geo_building_count?: number | null;
            /**
             * Geo Spread M
             * @description Dispersion of those buildings (m). Large = big footprint; render an area label rather than a precise dot.
             */
            geo_spread_m?: string | null;
        };
        /** PropertyType */
        PropertyType: {
            /** Id */
            id: number;
            /** Usage */
            usage: string;
            /** Prop Type */
            prop_type: string;
            /** Prop Subtype */
            prop_subtype?: string | null;
        };
        /** RankedEntity */
        RankedEntity: {
            /**
             * Capital Growth Cagr Pct
             * @description Annualized growth of the median sale AED/m2 between count-weighted anchor windows. Null when the span is under a year or there is not enough data — never a guess.
             */
            capital_growth_cagr_pct?: number | null;
            /**
             * Gross Rental Yield Pct
             * @description Median annual rent AED/m2 over median sale AED/m2, latest 12 months. GROSS: before service charges, vacancy and fees.
             */
            gross_rental_yield_pct?: number | null;
            /**
             * Gross Total Return Pct
             * @description capital_growth_cagr_pct + gross_rental_yield_pct, the NCREIF/MSCI income+capital decomposition. Null unless both halves exist — a missing half is never treated as zero.
             */
            gross_total_return_pct?: number | null;
            /** Median Sale Aed M2 */
            median_sale_aed_m2?: number | null;
            /** Median Rent Aed M2 Year */
            median_rent_aed_m2_year?: number | null;
            /**
             * Years
             * @description Span between anchor midpoints.
             */
            years?: number | null;
            start?: components["schemas"]["Anchor"] | null;
            end?: components["schemas"]["Anchor"] | null;
            /**
             * Sale Sample Size
             * @default 0
             */
            sale_sample_size: number;
            /**
             * Rent Sample Size
             * @default 0
             */
            rent_sample_size: number;
            /**
             * Months Covered
             * @default 0
             */
            months_covered: number;
            /** Month From */
            month_from?: string | null;
            /** Month To */
            month_to?: string | null;
            /** Id */
            id: number;
            /** Name En */
            name_en: string;
            /** Usage */
            usage?: string | null;
            /**
             * Sample Size
             * @description Buildings: sales in the trailing 12 months.
             */
            sample_size?: number | null;
            /** Sample Size Lifetime */
            sample_size_lifetime?: number | null;
            /** Median Sale Aed M2 Lifetime */
            median_sale_aed_m2_lifetime?: number | null;
            /** Cagr Sample Size */
            cagr_sample_size?: number | null;
            /**
             * Sample Tier
             * @description Buildings only: strong / thin / insufficient. Quote 'thin' and 'insufficient' figures with that caveat attached.
             */
            sample_tier?: string | null;
            /**
             * Income Metrics Unavailable
             * @description Present on buildings: states that yield cannot exist at this grain, so a null is not read as missing data.
             */
            income_metrics_unavailable?: string | null;
        };
        /** RankingResponse */
        RankingResponse: {
            /** Methodology */
            methodology: string;
            /**
             * Caveats
             * @description Limitations that must be repeated alongside any number here.
             */
            caveats: string[];
            /** Entity */
            entity: string;
            /** Metric */
            metric: string;
            /**
             * Metric Field
             * @description The response field ranked on.
             */
            metric_field: string;
            /** Items */
            items: components["schemas"]["RankedEntity"][];
            /** Applied */
            applied: {
                [key: string]: unknown;
            };
            /** Entities Considered */
            entities_considered: number;
            /**
             * Entities Excluded Insufficient Data
             * @description Entities dropped because the metric could not be computed honestly at this min_sample. A large number means the ranking covers a small slice of the city.
             */
            entities_excluded_insufficient_data: number;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** RentContract */
        RentContract: {
            /** Source Id */
            source_id: number;
            /** Source Code */
            source_code: string;
            /** Is Government */
            is_government: boolean;
            /** Source Url */
            source_url: string;
            /** Source Ref */
            source_ref?: string | null;
            /** Id */
            id: number;
            /** Contract Id */
            contract_id?: string | null;
            /** Line Number */
            line_number?: number | null;
            /**
             * No Of Prop
             * @description Properties covered by the contract. Amounts below are already divided by this, so they are per property.
             */
            no_of_prop?: number | null;
            /**
             * Registration Date
             * @description When the contract was registered. Gateway rows only.
             */
            registration_date?: string | null;
            /**
             * Start Date
             * @description Lease start. Can be years ahead of registration.
             */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /**
             * Version
             * @description New | Renew.
             */
            version?: string | null;
            /** Is Freehold */
            is_freehold?: boolean | null;
            /** Rooms */
            rooms?: string | null;
            /** Area Id */
            area_id: number;
            /** Area Name En */
            area_name_en: string;
            /** Project Id */
            project_id?: number | null;
            /** Project Name En */
            project_name_en?: string | null;
            /** Usage */
            usage?: string | null;
            /** Prop Type */
            prop_type?: string | null;
            /** Prop Subtype */
            prop_subtype?: string | null;
            /** Actual Area M2 */
            actual_area_m2?: string | null;
            /**
             * Annual Amount Aed
             * @description Per property, per year.
             */
            annual_amount_aed: string;
            /** Contract Amount Aed */
            contract_amount_aed?: string | null;
            /** Rent Per M2 Year */
            rent_per_m2_year?: string | null;
        };
        /**
         * ResolvedEntity
         * @description How a `q=` string was turned into an id.
         *
         *     Returned alongside the data so a client (or a model) can see exactly which
         *     entity the numbers describe, and how confident the match was.
         */
        ResolvedEntity: {
            /**
             * Query
             * @description The `q=` value that was resolved.
             */
            query: string;
            /** Id */
            id: number;
            /** Name En */
            name_en: string;
            /** Similarity */
            similarity: number;
            /**
             * Runners Up
             * @description Next-best matches, for transparency about near-misses.
             */
            runners_up?: components["schemas"]["EntityCandidate"][];
        };
        /** SaleTransaction */
        SaleTransaction: {
            /** Source Id */
            source_id: number;
            /** Source Code */
            source_code: string;
            /** Is Government */
            is_government: boolean;
            /** Source Url */
            source_url: string;
            /** Source Ref */
            source_ref?: string | null;
            /** Id */
            id: number;
            /** Txn Number */
            txn_number: string;
            /**
             * Txn Key
             * @description Normalized '{procedure}-{year}-{seq}'. Identifies the same Sales transaction across both sources; not unique for mortgages/gifts.
             */
            txn_key?: string | null;
            /**
             * Txn Date
             * Format: date-time
             */
            txn_date: string;
            /**
             * Txn Group
             * @description Sales | Mortgage | Gifts.
             */
            txn_group: string;
            /** Procedure Name */
            procedure_name?: string | null;
            /** Is Offplan */
            is_offplan: boolean;
            /**
             * Is Freehold
             * @description Null means unknown — the historical CSV has no such column.
             */
            is_freehold?: boolean | null;
            /** Rooms */
            rooms?: string | null;
            /** Parking */
            parking?: string | null;
            /** Area Id */
            area_id: number;
            /** Area Name En */
            area_name_en: string;
            /** Project Id */
            project_id?: number | null;
            /** Project Name En */
            project_name_en?: string | null;
            /** Usage */
            usage?: string | null;
            /** Prop Type */
            prop_type?: string | null;
            /** Prop Subtype */
            prop_subtype?: string | null;
            /** Actual Area M2 */
            actual_area_m2?: string | null;
            /** Amount Aed */
            amount_aed: string;
            /** Price Per M2 */
            price_per_m2?: string | null;
        };
        /** SeriesPoint */
        SeriesPoint: {
            /**
             * Month
             * Format: date
             */
            month: string;
            /** Sale Median Price M2 */
            sale_median_price_m2?: number | null;
            /**
             * Sale Cnt
             * @default 0
             */
            sale_cnt: number;
            /** Rent Median Annual M2 */
            rent_median_annual_m2?: number | null;
            /**
             * Rent Cnt
             * @default 0
             */
            rent_cnt: number;
        };
        /** Source */
        Source: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Base Url */
            base_url: string;
            /** License */
            license?: string | null;
            /**
             * Is Government
             * @description True for verified government data; false for third-party mirrors.
             */
            is_government: boolean;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Refresh Token
             * @description Only returned by /auth/login, not by /auth/refresh.
             */
            refresh_token?: string | null;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /**
             * Expires In
             * @description Access token lifetime, seconds.
             */
            expires_in: number;
        };
        /**
         * Usage
         * @description A raw `usage` value exactly as it appears in the data.
         *
         *     Not normalized on purpose: the real values include Arabic text and near
         *     duplicates, and there is **no 'office' category**. Listing them is how a
         *     caller discovers the true vocabulary instead of inventing one.
         */
        Usage: {
            /** Usage */
            usage: string;
            /** Property Type Count */
            property_type_count: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** YoYStep */
        YoYStep: {
            /** Year */
            year: number;
            /** Value Aed M2 */
            value_aed_m2?: number | null;
            /**
             * Sample Size
             * @default 0
             */
            sample_size: number;
            /** Yoy Change Pct */
            yoy_change_pct?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    metrics_meta_metrics_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    coverage_meta_coverage_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_areas_dimensions_areas_get: {
        parameters: {
            query?: {
                /** @description Fuzzy name search (pg_trgm trigrams). Lexical, so acronyms like 'JVC' do not match — use the full name. */
                q?: string | null;
                /** @description true = has any geometry (renderable at least as a point). Omit for no filtering; the API never hides data by default. */
                has_geo_data?: boolean | null;
                /** @description polygon = has a boundary (needed for choropleths); point = has a centroid (needed for pin maps). These sets differ materially. */
                geo_level?: ("point" | "polygon") | null;
                limit?: number | null;
                offset?: number | null;
            };
            header?: {
                authorization?: string | null;
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Area_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_area_dimensions_areas__area_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-api-key"?: string | null;
            };
            path: {
                area_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Area"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_dimensions_projects_get: {
        parameters: {
            query?: {
                /** @description Fuzzy name search (pg_trgm trigrams). Lexical, so acronyms like 'JVC' do not match — use the full name. */
                q?: string | null;
                area_id?: number | null;
                developer_id?: number | null;
                status?: string | null;
                /** @description The same name can exist as both master and regular. */
                is_master?: boolean | null;
                /** @description true = has any geometry (renderable at least as a point). Omit for no filtering; the API never hides data by default. */
                has_geo_data?: boolean | null;
                /** @description polygon = has a boundary (needed for choropleths); point = has a centroid (needed for pin maps). These sets differ materially. */
                geo_level?: ("point" | "polygon") | null;
                limit?: number | null;
                offset?: number | null;
            };
            header?: {
                authorization?: string | null;
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Project_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_dimensions_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-api-key"?: string | null;
            };
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_buildings_dimensions_buildings_get: {
        parameters: {
            query?: {
                /** @description Fuzzy name search (pg_trgm trigrams). Lexical, so acronyms like 'JVC' do not match — use the full name. */
                q?: string | null;
                area_id?: number | null;
                project_id?: number | null;
                /** @description true = has any geometry (renderable at least as a point). Omit for no filtering; the API never hides data by default. */
                has_geo_data?: boolean | null;
                limit?: number | null;
                offset?: number | null;
            };
            header?: {
                authorization?: string | null;
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Building_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_building_dimensions_buildings__building_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-api-key"?: string | null;
            };
            path: {
                building_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Building"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_developers_dimensions_developers_get: {
        parameters: {
            query?: {
                /** @description Fuzzy name search (pg_trgm trigrams). Lexical, so acronyms like 'JVC' do not match — use the full name. */
                q?: string | null;
                limit?: number | null;
                offset?: number | null;
            };
            header?: {
                authorization?: string | null;
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Developer_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_property_types_dimensions_property_types_get: {
        parameters: {
            query?: {
                usage?: string | null;
                limit?: number | null;
                offset?: number | null;
            };
            header?: {
                authorization?: string | null;
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_PropertyType_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_usages_dimensions_usages_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Usage"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_dimensions_sources_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Source"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_transactions_facts_transactions_get: {
        parameters: {
            query?: {
                area_id?: number | null;
                project_id?: number | null;
                /** @description Sales in one building. Linked on ~71.5% of transactions, so this returns a subset of a building's real activity — an empty result does not mean nothing sold there. */
                building_id?: number | null;
                date_from?: string | null;
                date_to?: string | null;
                /** @description Sales | Mortgage | Gifts. Sales for price analysis. */
                txn_group?: string | null;
                usage?: string | null;
                property_type_id?: number | null;
                is_offplan?: boolean | null;
                price_min?: number | null;
                price_max?: number | null;
                area_m2_min?: number | null;
                area_m2_max?: number | null;
                rooms?: string | null;
                limit?: number | null;
                offset?: number | null;
            };
            header?: {
                authorization?: string | null;
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_SaleTransaction_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rents_facts_rents_get: {
        parameters: {
            query?: {
                area_id?: number | null;
                project_id?: number | null;
                start_date_from?: string | null;
                start_date_to?: string | null;
                /** @description New | Renew. */
                version?: string | null;
                usage?: string | null;
                property_type_id?: number | null;
                annual_amount_min?: number | null;
                annual_amount_max?: number | null;
                /** @description Include leases starting after today. Off by default: advance leases run years ahead and would dominate the newest page. */
                include_future?: boolean;
                limit?: number | null;
                offset?: number | null;
            };
            header?: {
                authorization?: string | null;
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_RentContract_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    area_monthly_marts_area_monthly_get: {
        parameters: {
            query?: {
                /** @description Comma-separated ids, matching the multi-select UX: tick several entities, pull the whole selection in one request. Omit for all entities (subject to the page cap). */
                area_ids?: string | null;
                /** @description Resolve one area by fuzzy name instead of passing ids. */
                q?: string | null;
                usage?: string | null;
                month_from?: string | null;
                month_to?: string | null;
                /** @description Drop months with fewer than this many transactions. Some months hold a single sale whose 'median' is just that sale. */
                min_sample?: number | null;
                has_geo_data?: boolean | null;
                geo_level?: ("point" | "polygon") | null;
                /** @description Include months after today. The marts extend to 2028 because leases are registered years ahead; those months are real but describe contracts that have not started. */
                include_future?: boolean;
                limit?: number | null;
                offset?: number | null;
            };
            header?: {
                authorization?: string | null;
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MartPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    project_monthly_marts_project_monthly_get: {
        parameters: {
            query?: {
                /** @description Comma-separated ids, matching the multi-select UX: tick several entities, pull the whole selection in one request. Omit for all entities (subject to the page cap). */
                project_ids?: string | null;
                /** @description Resolve one project by fuzzy name instead of passing ids. */
                q?: string | null;
                /** @description Scopes `q=` resolution — project names repeat. */
                area_id?: number | null;
                usage?: string | null;
                month_from?: string | null;
                month_to?: string | null;
                /** @description Drop months with fewer than this many transactions. Some months hold a single sale whose 'median' is just that sale. */
                min_sample?: number | null;
                has_geo_data?: boolean | null;
                geo_level?: ("point" | "polygon") | null;
                /** @description Include months after today. The marts extend to 2028 because leases are registered years ahead; those months are real but describe contracts that have not started. */
                include_future?: boolean;
                limit?: number | null;
                offset?: number | null;
            };
            header?: {
                authorization?: string | null;
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MartPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    building_summary_marts_building_summary_get: {
        parameters: {
            query?: {
                /** @description Comma-separated ids, matching the multi-select UX: tick several entities, pull the whole selection in one request. Omit for all entities (subject to the page cap). */
                building_ids?: string | null;
                /** @description Resolve one building by fuzzy name instead of passing ids. */
                q?: string | null;
                /** @description Filters results, and scopes `q=` resolution. Building names repeat across Dubai more than area names do, so without this an ambiguous `q=` is the common case. */
                area_id?: number | null;
                usage?: string | null;
                /** @description Drop months with fewer than this many transactions. Some months hold a single sale whose 'median' is just that sale. */
                min_sample?: number | null;
                /** @description Filter by price-level reliability. */
                sample_tier?: ("strong" | "thin" | "insufficient") | null;
                limit?: number | null;
                offset?: number | null;
            };
            header?: {
                authorization?: string | null;
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildingSummaryPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    area_ranking_analytics_area_ranking_get: {
        parameters: {
            query?: {
                metric?: "capital_growth" | "gross_yield" | "total_return" | "sale_price_m2" | "rent_m2";
                entity?: "area" | "project" | "building";
                month_from?: string | null;
                month_to?: string | null;
                usage?: string | null;
                min_sample?: number | null;
                has_geo_data?: boolean | null;
                geo_level?: ("point" | "polygon") | null;
                limit?: number;
                /** @description true ranks cheapest/lowest first. */
                ascending?: boolean;
            };
            header?: {
                authorization?: string | null;
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    growth_analytics_growth_get: {
        parameters: {
            query?: {
                entity?: "area" | "project";
                /** @description Exact id. Alternative to q=. */
                id?: number | null;
                /** @description Fuzzy name; 422 if ambiguous. */
                q?: string | null;
                /** @description Scopes q= for projects. */
                area_id?: number | null;
                month_from?: string | null;
                month_to?: string | null;
                usage?: string | null;
                min_sample?: number | null;
            };
            header?: {
                authorization?: string | null;
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrowthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    yields_analytics_yield_get: {
        parameters: {
            query?: {
                entity?: "area" | "project";
                month_from?: string | null;
                month_to?: string | null;
                usage?: string | null;
                min_sample?: number | null;
                has_geo_data?: boolean | null;
                geo_level?: ("point" | "polygon") | null;
                limit?: number;
                ascending?: boolean;
            };
            header?: {
                authorization?: string | null;
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_analytics_compare_get: {
        parameters: {
            query?: {
                dimension?: "usage" | "area" | "project" | "mixed";
                /** @description Comma-separated values, names or ids. With dimension=mixed, each value is 'type:value', e.g. 'area:55' or 'building:LAKE TERRACE'. */
                values?: string;
                month_from?: string | null;
                month_to?: string | null;
                min_sample?: number | null;
            };
            header?: {
                authorization?: string | null;
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    areas_geojson_geo_areas_get: {
        parameters: {
            query?: {
                /** @description polygon falls back to the centroid when no boundary exists. */
                geo_level?: "point" | "polygon";
                usage?: string | null;
                month_from?: string | null;
                month_to?: string | null;
                min_sample?: number | null;
                /** @description Comma-separated ids. */
                area_ids?: string | null;
            };
            header?: {
                authorization?: string | null;
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    projects_geojson_geo_projects_get: {
        parameters: {
            query?: {
                /** @description Comma-separated ids. */
                project_ids?: string | null;
            };
            header?: {
                authorization?: string | null;
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    buildings_geojson_geo_buildings_get: {
        parameters: {
            query?: {
                /** @description Scope to one area (the common map case). */
                area_id?: number | null;
                project_id?: number | null;
                /** @description Comma-separated ids. */
                building_ids?: string | null;
            };
            header?: {
                authorization?: string | null;
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
